<h1 align='center'> 파이썬과학프로그래밍기초 실습 6</h1>

<p style="text-align: right"> 2023.10.26.</p>


<div class="alert alert-block alert-info">
    
- 파일 이름에서 00000000을 자신의 학번으로, name을 자신의 이름으로 수정하세요.

- 다음 줄에 자신의 이름, 학번, 학과(전공)을 적으세요.

* 이름:김민준   &nbsp;&nbsp;          학번:20235128    &nbsp;&nbsp;         학과(전공):소프트웨어융합
    
</div>

- JupyterLab 문서의 최신 버전은 [JupyterLab Documentation](https://jupyterlab.readthedocs.io/en/stable/index.html#/)을  참고하라

- Markdown은 [Markdown Guide](https://www.markdownguide.org/)를 참고하라.
- [Markdown Cheat Sheet](https://www.markdownguide.org/cheat-sheet/)

* 제출 마감: **10월 25일 (수) 오후 10:00**까지 최종본을 SmartLEAD에 제출


### 예제 1. 행렬의 곱셈

아래 행렬의 곱셈을 손으로 직접 계산해 보자.

행렬의 곱셈은 다음을 참조하라.

https://en.wikipedia.org/wiki/Matrix_multiplication

행렬 ${\bf A}$와 ${\bf B}$가 각각 다음과 같다.
$${\bf A} = \begin{bmatrix}
1 & 2 & 3 \\ 4 & 5 & 6 
 \end{bmatrix}
 $$
 
$$ {\bf B} = \begin{bmatrix}
 1 & 2  \\ 3 & 4 \\ 5 & 6
 \end{bmatrix}
 $$ 

두 행렬 ${\bf A}$와 ${\bf B}$를 곱하기 위해서는 행렬 ${\bf A}$의 열의 개수와 행렬 ${\bf  B}$의 행의 개수가 같아야 한다.

다음 두 행렬에서 ${\bf A}$는 $2\times 3$ (2행 3열) 행렬이고, ${\bf B}$는 $3\times 2$ (3행 2열) 행렬이므로  ${\bf AB}$를 구할 수 있다.


행렬  ${\bf A}$와 ${\bf B}$의 곱은 다음과 같이 계산된다.

$$  {\bf C} = {\bf AB} = \begin{bmatrix}
 1 & 2 & 3\\ 4 & 5 & 6 
 \end{bmatrix}
 \begin{bmatrix}
 1 & 2  \\ 3 & 4 \\ 5 & 6
 \end{bmatrix}
  = \begin{bmatrix}
22 & 28 \\
49 & 64 
 \end{bmatrix}
 = \begin{bmatrix}
c_{11} & c_{12} \\
c_{21} & c_{22} 
 \end{bmatrix}
$$

행렬 $ {\bf C}$의 각 원소는 다음과 같이 계산된다.

$$ {\bf C} = \begin{bmatrix}
\color{red}{c_{11}} & c_{12} \\
c_{21} & c_{22} 
 \end{bmatrix} = \begin{bmatrix}
 \color{red}{1} & \color{red}{2} & \color{red}{3} \\ 4 & 5 & 6 
 \end{bmatrix}
 \begin{bmatrix}
 \color{red}{1} & 2  \\ \color{red}{3} & 4 \\ \color{red}{5} & 6
 \end{bmatrix} = \begin{bmatrix}
 \color{red}{(1)(1) + (2)(3) + (3)(5)} & (1)(2) + (2)(4) + (3)(6) \\
 (4)(1) + (5)(3) + (6)(5) & (4)(2) + (5)(4) + (6)(6)
 \end{bmatrix}
 $$ 

$$ {\bf C} = \begin{bmatrix}
c_{11} & \color{red}{c_{12}} \\
c_{21} & c_{22} 
 \end{bmatrix} =  \begin{bmatrix}
 \color{red}{1} & \color{red}{2} & \color{red}{3} \\ 4 & 5 & 6 
 \end{bmatrix}
 \begin{bmatrix}
 1 & \color{red}{2}  \\ 3 & \color{red}{4} \\ 5 & \color{red}{6}
 \end{bmatrix} = \begin{bmatrix}
 (1)(1) + (2)(3) + (3)(5) & \color{red}{(1)(2) + (2)(4) + (3)(6)} \\
 (4)(1) + (5)(3) + (6)(5) & (4)(2) + (5)(4) + (6)(6)
 \end{bmatrix}
 $$

$$ {\bf C} = \begin{bmatrix}
c_{11} & c_{12} \\
\color{red}{c_{21}} & c_{22} 
 \end{bmatrix}
= \begin{bmatrix}
 1 & 2 & 3 \\ \color{red}{4} & \color{red}{5} & \color{red}{6}
 \end{bmatrix}
 \begin{bmatrix}
 \color{red}{1} & 2  \\ \color{red}{3} & 4 \\ \color{red}{5} & 6
 \end{bmatrix} = \begin{bmatrix}
 (1)(1) + (2)(3) + (3)(5) & (1)(2) + (2)(4) + (3)(6) \\
 \color{red}{(4)(1) + (5)(3) + (6)(5)} & (4)(2) + (5)(4) + (6)(6)
 \end{bmatrix}
 $$

$$ {\bf C} = \begin{bmatrix}
c_{11} & c_{12} \\
c_{21} & \color{red}{c_{22}} 
 \end{bmatrix} = \begin{bmatrix}
 1 & 2 & 3 \\ \color{red}{4} & \color{red}{5} & \color{red}{6}
 \end{bmatrix}
 \begin{bmatrix}
  1 & \color{red}{2}  \\ 3 & \color{red}{4} \\ 5 & \color{red}{6}
 \end{bmatrix} = \begin{bmatrix}
 (1)(1) + (2)(3) + (3)(5) & (1)(2) + (2)(4) + (3)(6) \\
 (4)(1) + (5)(3) + (6)(5) & \color{red}{(4)(2) + (5)(4) + (6)(6)}
 \end{bmatrix}
 $$

행렬 ${\bf C}$는 다음과 같이 계산된다.

$$ {\bf C} = \begin{bmatrix}
c_{11} & c_{12} \\
c_{21} & c_{22} 
 \end{bmatrix}
 = \begin{bmatrix}
 (1)(1) + (2)(3) + (3)(5) & (1)(2) + (2)(4) + (3)(6) \\
 (4)(1) + (5)(3) + (6)(5) & (4)(2) + (5)(4) + (6)(6)
 \end{bmatrix}
 = \begin{bmatrix}
22 & 28 \\
49 & 64 
 \end{bmatrix}
 $$

### 예제 2.
예제 1에서 구한 행렬 ${\bf C}$의 $c_{11}$ 구하는 프로그램을 작성하라.

주의: 행렬 원소의 인덱스는 1부터 시작하지만, Python 리스트 원소의 인덱스는 0부터 시작한다.

In [17]:
import numpy as np

A = [[1,2,3], [4,5,6]]
B = [[1,2], [3,4], [5,6]]

In [18]:
c11 = A[0][0] * B[0][0] + A[0][1] * B[1][0] + A[0][2] * B[2][0]
print(c11)

22


### 문제 1.
예제 2에서 구한 방법을 사용하여 행렬 ${\bf C}$의 $c_{12}, c_{21}, c_{22}$를 각각 구하는 프로그램을 작성하라.

In [19]:
A = [[1,2,3], [4,5,6]]
B = [[1,2], [3,4], [5,6]]

c12 = A[0][0]*B[0][1] + A[0][1]*B[1][1] + A[0][2]*B[2][1]
print(c12)

28


In [20]:
A = [[1,2,3], [4,5,6]]
B = [[1,2], [3,4], [5,6]]

c21 = A[1][0]*B[0][0] + A[1][1]*B[1][0] + A[1][2]*B[2][0]
print(c21)

49


In [21]:
A = [[1,2,3], [4,5,6]]
B = [[1,2], [3,4], [5,6]]

c22 = A[1][0]*B[0][1] + A[1][1]*B[1][1] + A[1][2]*B[2][1]
print(c22)

64


### 예제 3.
예제 2에서 구한 행렬 ${\bf C}$의 $c_{11}$ 구하는 프로그램을 for loop을 이용하여 다시 작성하라.

In [22]:
c11 = 0
for k in range(3):
    c11 += A[0][k] * B[k][0]
print(c11)

22


### 문제 2.
예제 3을 참고해서 문제 1에서 구한 행렬 ${\bf C}$의 $c_{12}, c_{21}, c_{22}$를 각각 구하는 프로그램을 for loop을 이용해서 다시 작성하라.

In [23]:
c12 = 0
for k in range(3):
    c12 += A[0][k] * B[k][1]
print(c12)

28


In [24]:
c21 = 0
for k in range(3):
    c21 += A[1][k] * B[k][0]
print(c21)

49


In [25]:
c22 = 0
for k in range(3):
    c22 += A[1][k] * B[k][1]
print(c22)

64


### 예제 4.
예제 3에서 구한 행렬 ${\bf C}$의 $c_{11}$ 구하는 프로그램을 다음과 같이 리스트 컴프리헨션 sum() 함수를 이용하여 계산할 수 있다.

In [26]:
c11 = sum([A[0][k] * B[k][0] for k in range(3)])    
print(c11)

22


### 문제 3.
예제 4를 참고해서 문제 2에서 구한 행렬 ${\bf C}$의 $c_{12}, c_{21}, c_{22}$를 각각 구하는 프로그램을 다시 작성하라.

In [27]:
c12 = sum([A[0][k] * B[k][1] for k in range(3)])
print(c12)

28


In [28]:
c21 = sum([A[1][k] * B[k][0] for k in range(3)])
print(c21)

49


In [29]:
c22 = sum([A[1][k] * B[k][1] for k in range(3)])
print(c22)

64


### 예제 5.

앞에서 두 행렬을 각각 다음과 같이 네스티드 리스트로 표현했을 때, 두 행렬의 행과 열의 개수를 각각 구하라.

```
A = [[1,2,3], [4,5,6]]
B = [[1,2], [3,4], [5,6]]
```

In [30]:
# A의 행의 개수
print(len(A))

2


In [31]:
# A의 열의 개수
print(len(A[0]))

3


### 예제 6.
네스티드 리스트 A, B를 파라미터로 받아들여 행렬의 곱셈을 구하는 함수를 작성하라.

In [35]:
A = [[1,2,3], [4,5,6]]
B = [[1,2], [3,4], [5,6]]

def matrix_mul_list(A, B):
    if len(A[0]) != len(B):
        print('Two matrices cannot be multiplied.')
        return []
    else:
        C = []
        for n in range(len(A)):
            row = []
            for m in range(len(B[0])):
                s = 0
                for k in range(len(A[0])):
                    s += A[n][k] * B[k][m]
                row.append(s)
            C.append(row)
        return C
    
matrix_mul_list(A, B)

[[22, 28], [49, 64]]

### 문제 4.

예제 4와 문제 3을 참고해서, 예제 6의 프로그램을 수정한 함수 matrix_mul_list_2(A, B)를 아래 셀에 완성하라.

In [41]:
def matrix_mul_list_2(A, B):
    if len(A[0]) != len(B):
        print('Two matrices cannot be multiplied.')
        return []
    else:
        C = [[sum(A[i][k] * B[k][j] for k in range(len(A[0]))) for j in range(len(B[0]))]for i in range(len(A))]
        return C

In [42]:
matrix_mul_list_2(A, B)

[[22, 28], [49, 64]]

In [43]:
matrix_mul_list_2(B, A)

[[9, 12, 15], [19, 26, 33], [29, 40, 51]]

### 예제 5. (인덱스를 사용하지 않고 네스티드 리스트의 원소 접근하기)

인덱스를 사용하지 않고 리스트 A = [[1,2,3], [4,5,6]]의 원소 1, 2, 3, 4, 5, 6 을 차례대로 콘솔에 출력하라

In [44]:
for row in A:
    for e in row:
        print(e, end=' ')
    print()

1 2 3 
4 5 6 


### 문제 5.

아래 셀의 프로그램에서 zip() 함수가 하는 역할을 설명하라.

In [45]:
for row in zip([1,2], [3,4], [5,6]):
    print(row)

(1, 3, 5)
(2, 4, 6)


**답**
zip() 함수는 주어진 여러 개의 iterable(반복 가능한) 객체(리스트, 튜플, 등)를 병렬로 <br>
묶어주는 역할을 합니다. 각 입력 iterable에서 동일한 위치에 있는 요소들을 튜플로 묶어 <br>
새로운 iterable을 생성합니다. 이때, 입력 iterable 중 가장 짧은 길이를 가진 iterable이 <br>
기준이 되어, 그 길이만큼만 요소가 묶입니다. <br>


예를 들어, 주어진 코드에서 zip([1,2], [3,4], [5,6])는 [1,2], [3,4], [5,6] 이렇게 <br>
세 개의 iterable에서 동일한 위치에 있는 요소를 묶어서 다음과 같이 튜플을 생성합니다: <br>


(1, 3, 5)<br>
(2, 4, 6)<br>

### 문제 6.

아래 셀의 프로그램에서 zip(*B) 가 하는 역할을 설명하라.

In [ ]:
print(B)
print(list(zip(*B)))

**답**
주어진 코드에서 zip(*B)의 역할은 다음과 같습니다:

B 리스트의 원소들을 분해: *B를 사용하면 B 리스트의 각 원소를 개별적인 인수로 분해합니다. 이것은 언패킹(unpacking)이라고도 합니다.

zip() 함수 적용: 분해된 원소들을 zip() 함수의 인수로 전달합니다. zip() 함수는 각 입력 iterable(리스트)에서 동일한 위치에 있는 요소들을 묶어서 튜플을 생성합니다.

튜플의 리스트 반환: zip() 함수의 결과는 각 원소를 튜플로 묶어서 리스트로 반환됩니다.

### 예제 7.

리스트 B로 표현된 행렬에서 두 컬럼을 콘솔에 출력하라.

In [ ]:
for col in zip(*B):
    print(col)

### 예제 8.

아래 셀은 예제 6의 프로그램을 인덱스를 사용하지 않고 변경한 프로그램이다.

In [ ]:
def matrix_mul_list_3(A, B):
    if len(A[0]) != len(B):
        print('Two matrices cannot be multiplied.')
        return []
    else:
        C = []
        for A_row in A:
            C_row = []
            for B_col in zip(*B):
                s = 0
                for a, b in zip(A_row, B_col):
                    s += a * b
                C_row.append(s)
            C.append(C_row)
        return C

In [ ]:
matrix_mul_list_3(A, B)

### 문제 7.

아래 셀에 주어진 함수는 예제 8에 주어진 함수를 리스트 컴프리헨션을 사용하여 다시 작성한 것이다. 빈 부분을 완성하라.

In [46]:
def matrix_mul_list_4(A, B):
    if len(A[0]) != len(B):
        print('Two matrices cannot be multiplied.')
        return []
    else:
        C = [[sum(A[i][k] * B[k][j] for k in range(len(A[0]))) for j in range(len(B[0]))]for i in range(len(A))]
        return C

In [47]:
matrix_mul_list_4(A, B)

[[22, 28], [49, 64]]

### 문제 8. 
zip 함수를 이용하면 두 개의 iterables의 같은 위치에 있는 원소의 tuple을 원소로 갖는 iterable을 만들 수 있다.

```
provinces = ['경기도', '강원도']
cities = ['수원', '춘천']
result = list(zip(provinces, cities))
print(result)
```

위 네 줄을 실행하면 다음 결과를 얻는다.

[('경기도', '수원'), ('강원도', '춘천')]


map 함수를 이용하여 result를 구하여라.

In [18]:
provinces = ['경기도', '강원도']
cities = ['수원', '춘천']
result = list(map(lambda x, y: (x, y), provinces, cities))
print(result)

[('경기도', '수원'), ('강원도', '춘천')]


In [12]:
'''Function'''
class Matrix:
    @staticmethod
    def scalarMultiplication(k:int, a:list) -> list:
        n:list=[]
        for r in range(0, len(a), 1):
            cells:list=[]
            for c in range(0, len(a[0]), 1):
                cells.append(a[r][c]*k)
            n.append(cells)
        return n
    @staticmethod
    def multiplication(a:list, b:list) -> list:
        if(len(a[0])!=len(b)):
            return []
        else:
            n:list=[]
            for r in range(0, len(a), 1):
                cells:list=[]
                for c in range(0, len(b[0]), 1):
                    cell:int=0
                    for i in range(0, len(a), 1):
                        cell += a[r][i]*b[i][c]
                    cells.append(cell)
                n.append(cells)
            return n
    @staticmethod
    def addition(a:list, b:list) -> list:
        if(len(a)!=len(b) or len(a[0])!=len(b[0])):
            return []
        else:
            n:list=[]
            for r in range(0, len(a), 1):
                cells:list=[]
                for c in range(0, len(a[0]), 1):
                    cells.append(a[r][c]+b[r][c])
                n.append(cells)
            return n
    @staticmethod
    def transposed(a:list) -> list:
        n:list=[]
        for r in range(0, len(a[0]), 1):
            cells:list=[]
            for c in range(0, len(a), 1):
                cells.append(a[c][r])
            n.append(cells)
        return n
'''Main'''
def main():
    A = [[1 , 2 , 3 ],
         [4 , 5 , 6 ]]
    
    B = [[7 , 8 ],
         [9 , 10],
         [11, 12]]

    C = [[7 , 8 , 9 ],
         [10, 11, 12]]

    matrix:Matrix=Matrix()
    print(matrix.scalarMultiplication(3, A), end="\n")
    print(matrix.addition(A, C), end="\n")
    print(matrix.multiplication(A, B), end="\n")
    print(matrix.transposed(A), end="\n")

if __name__ == "__main__":
    main()

[[3, 6, 9], [12, 15, 18]]
[[8, 10, 12], [14, 16, 18]]
[[25, 28], [73, 82]]
[[1, 4], [2, 5], [3, 6]]


In [16]:
'''import'''
import numpy
'''main'''
def main():
    A = [[1 , 2 , 3 ],
         [4 , 5 , 6 ]]

    B = [[7 , 8 ],
         [9 , 10],
         [11, 12]]
    
    A = numpy.array(A)
    B = numpy.array(B)
    print(A, end="\n")
    print(B, end="\n")
    print(numpy.dot(A, B), end="\n") #내적
    print(type(A), end="\n")
    
if __name__=="__main__":
    main()

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]
<class 'numpy.ndarray'>


In [17]:
'''import'''
import numpy
'''main'''
def main():
    A = [[1 , 2 , 3 ],
         [4 , 5 , 6 ]]

    B = [[7 , 8 ],
         [9 , 10],
         [11, 12]]

    A = numpy.matrix(A)
    B = numpy.matrix(B)
    print(A, end="\n")
    print(B, end="\n")
    print(numpy.dot(A, B), end="\n") #내적
    print(type(A), end="\n")

if __name__=="__main__":
    main()

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]
<class 'numpy.matrix'>


map, reduce 더 공부하기