<h1 align='center'> 파이썬과학프로그래밍기초 실습 7</h1>

<p style="text-align: right"> 2023.11.7.</p>

### <div class="alert alert-block alert-info">
    
- 파일 이름에서 00000000을 자신의 학번으로, name을 자신의 이름으로 수정하세요.

- 다음 줄에 자신의 이름, 학번, 학과(전공)을 적으세요.

* 이름:김민준   &nbsp;&nbsp;          학번:20235128    &nbsp;&nbsp;         학과(전공):소프트웨어융합
    
</div>

- Jupyter notebook에 대한 설명은 [The Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/stable/)을  참고하라

- Markdown은 [Markdown Guide](https://www.markdownguide.org/)를 참고하라.
- [Markdown Cheat Sheet](https://www.markdownguide.org/cheat-sheet/)

* 과제 제출: 12월 1일 (수) 오후 10:00까지 최종본 제출. 


#### 아래 셀에 다음 명령을 실행하라.

```
import numpy as np
np.__version__
```


In [1]:
import numpy as np
np.__version__

'1.26.2'

### 예제 1.
NumPy의 arange를 사용하여 다음 ndarray를 만들어라.

```
array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int16)
```

In [2]:
import numpy as np

np.arange(8, dtype=np.int16)

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int16)

### 예제 2.
NumPy의 arange를 사용하여 다음 ndarray를 만들어라.

```
array([ 0,  2,  4,  6,  8, 10, 12, 14], dtype=int64)
```

In [3]:
np.arange(0, 16, 2, dtype=np.int64)


array([ 0,  2,  4,  6,  8, 10, 12, 14], dtype=int64)

### 예제 3.
NumPy의 arange를 사용하여 다음 ndarray를 만들어라.

```
array([1. , 1.2, 1.4, 1.6, 1.8])
```

In [4]:
np.arange(1, 2, 0.2)


array([1. , 1.2, 1.4, 1.6, 1.8])

### 예제 4.
NumPy의 linspace를 사용하여 다음 ndarray를 만들어라.

```
array([ 0. ,  2.5,  5. ,  7.5, 10. ])
```

In [5]:
np.linspace(0, 10, 5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### 예제 5.
NumPy의 linspace를 사용하여 다음 ndarray를 만들어라.

```
array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])
```

In [6]:
np.linspace(1, 10, 5)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### 예제 6.
NumPy의 arange를 사용하여 다음 ndarray를 만들어라.

```
array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])
```

In [7]:
np.arange(1, 10.1, 2.25)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### 예제 7.
NumPy의 arange와 reshape을 사용하여 다음 ndarray를 만들어라.

```
array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24], dtype=int64)
```

In [8]:
np.arange(2, 25, 2, dtype=np.int64).reshape(3,4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]], dtype=int64)

### 문제 1.
예제 7에서 만든 ndarray에서 4, 12, 20의 합 36을 출력하는 문장 2 개를 작성하라. (서로 다른 두 가지 방법으로 같은 결과를 출력하라)

In [9]:
x = np.arange(2, 25, 2, dtype=np.int64).reshape(3,4)
print(x, end="")

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

In [10]:
x = np.arange(2, 25, 2, dtype=np.int64).reshape(3, 4)
value_sum:np.int64 = 0
for row in x:
    value_sum += row[1]
print(value_sum, end="\n")

36


In [11]:
x = np.arange(2, 25, 2, dtype=np.int64).reshape(3, 4)
value_sum = x[:, 1].sum()
print(value_sum, end="\n")

36


### 문제 2.
예제 7에서 만든 ndarray에서 18, 20, 22, 24의 합 84를 출력하는 문장 3 개를 작성하라. (서로 다른 두 가지 방법으로 같은 결과를 출력하라)

In [12]:
x = np.arange(2, 25, 2, dtype=np.int64).reshape(3,4)
print(x, end="")

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

In [13]:
x = np.arange(2, 25, 2, dtype=np.int64).reshape(3,4)
value_sum:np.int64 = x[2][0]+x[2][1]+x[2][2]+x[2][3]
print(value_sum, end="")

84

In [14]:
x = np.arange(2, 25, 2, dtype=np.int64).reshape(3,4)
value_sum:np.int64 = 0
for cal in x[2]:
    value_sum += cal
print(value_sum, end="")

84

In [15]:
x = np.arange(2, 25, 2, dtype=np.int64).reshape(3,4)
value_sum:np.int64 = x[2, :].sum()
print(value_sum, end="")

84

### 문제 3.
예제 7에서 만든 ndarray에서 2, 12, 22의 합 36을 출력하는 문장을 작성하라.

In [16]:
x = np.arange(2, 25, 2, dtype=np.int64).reshape(3,4)
value_sum:np.int64 = 0
index:int = 0
for row in x:
    #print(row[index], end="\n")
    value_sum+=row[index]
    index+=1
print(value_sum, end="")

36

In [17]:
x = np.arange(2, 25, 2, dtype=np.int64).reshape(3,4)
print(np.diag(x).sum(), end="")

36

### 문제 4.
예제 7에서 만든 ndarray에서 4, 14, 24의 합 42을 출력하는 문장을 작성하라.

In [18]:
x = np.arange(2, 25, 2, dtype=np.int64).reshape(3,4)
value_sum:np.int64 = 0
index:int = 1
for row in x:
    #print(row[index], end="\n")
    value_sum+=row[index]
    index+=1
print(value_sum, end="")

42

In [19]:
x = np.arange(2, 25, 2, dtype=np.int64).reshape(3,4)
print(np.diag(x, 1).sum(), end="")

42

### 문제 5.
예제 7에서 만든 ndarray에서 10, 20의 합 30을 출력하는 문장을 작성하라.

In [20]:
x = np.arange(2, 25, 2, dtype=np.int64).reshape(3,4)
value_sum:np.int64 = 0
index:int = 0
for row in x[1:, :]:
    #print(row[index], end="\n")
    value_sum+=row[index]
    index+=1
print(value_sum, end="")

30

In [21]:
x = np.arange(2, 25, 2, dtype=np.int64).reshape(3,4)
print(np.diag(x, -1).sum(), end="")

30

### 예제 7. 축 방향으로 함수 적용하기 
```
apply_along_axis(func1d, axis, arr, *args, **kwargs)
```


In [22]:
np.random.seed(1)
a = np.random.randint(1, 50, (3,5))
print(a)

[[38 44 13  9 10]
 [12  6 16  1 17]
 [ 2 13  8 46  7]]


#### 7.1 축 방향으로 정렬하기

In [23]:
np.apply_along_axis(sorted, 0, a)

array([[ 2,  6,  8,  1,  7],
       [12, 13, 13,  9, 10],
       [38, 44, 16, 46, 17]])

#### 7.2 축 방향으로 사용자 정의 함수 적용하기

In [24]:
f = lambda x, y: x**y + 1

In [25]:
np.apply_along_axis(f, 1, a, 2)

array([[1445, 1937,  170,   82,  101],
       [ 145,   37,  257,    2,  290],
       [   5,  170,   65, 2117,   50]])

In [26]:
a**2 + 1

array([[1445, 1937,  170,   82,  101],
       [ 145,   37,  257,    2,  290],
       [   5,  170,   65, 2117,   50]])

In [27]:
print(a)
min_a = np.apply_along_axis(min, 1, a)
print(a)
print(min_a)

[[38 44 13  9 10]
 [12  6 16  1 17]
 [ 2 13  8 46  7]]
[[38 44 13  9 10]
 [12  6 16  1 17]
 [ 2 13  8 46  7]]
[9 1 2]


### 문제 6. 
'fake_student_records.csv' 파일은 가상의 학생들의 시험 성적을 기록한 파일이다.
아래 프로그램은 이 파일의 한 줄을 딕셔너리로 변환하여 콘솔에 출력하는 프로그램이다.
```
import csv
with open('fake_student_records.csv', mode='r', encoding='utf-8') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
        print(row)
```
이 프로그램을 응용하여 학생들이 8 번 제출한 과제 성적을를 2차원 numpy array로 변환한 후에 각 시험의 평균을 소숫점 첫째자리까지 콘솔에 출력하라.

정답은 다음과 같다.
```
[75.5 73.2 77.9 74.1 75.4 75.9 73.2 73.7]
```

In [28]:
import csv
import numpy as np

score = []

with open('fake_student_records.csv', mode='r', encoding='utf-8') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
        scores = [int(row[f'과제{i}']) for i in range(1, 9)]
        score.append(scores)

result = np.round(np.sum(score, axis=0)/np.array(score).shape[0], 1)
print(result, end="")

[73.7 72.6 73.8 74.7 73.7 71.5 72.8 76.2]

In [29]:
import csv
import numpy as np

scores = []
exams = ["과제"+str(n) for n in range(1, 9)]

with open('fake_student_records.csv', mode='r', encoding='utf-8') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
        scores.append([int(row[k]) for k in exams])

scores = np.array(scores)
print(scores[:, 2].sum(), end="\n")
scores = [scores[:, n]/len(scores) for n in range(len(scores))]
print(scores)
scores.mean(0).round(1)

5608


IndexError: index 8 is out of bounds for axis 1 with size 8

### 문제 7.
다음 ndarray를 만들고 변수 a에 이 객체를 할당하라. 단, 모든 원소를 직접 나열하면 안된다.

```
array([[[  3   6   9  12  15]
       [ 18  21  24  27  30]
       [ 33  36  39  42  45]]

      [[ 48  51  54  57  60]
       [ 63  66  69  72  75]
       [ 78  81  84  87  90]]

      [[ 93  96  99 102 105]
       [108 111 114 117 120]
       [123 126 129 132 135]]

      [[138 141 144 147 150]
       [153 156 159 162 165]
       [168 171 174 177 180]]])
```

In [ ]:
import numpy as np

a = np.arange(3, 181, 3).reshape(4, 3, 5)
print(a)

### 문제 8.
아래와 같이 a에 2 차원 배열이 할당되었다고 가정하자.
```
a = [[38 44 13  9 10]
     [12  6 16  1 17]
     [ 2 13  8 46  7]]
```
axis 0 방향으로 최대값에는 5를 더하고 최소값에는 5를 빼면 a는 다음과 같이 변한다.
```
a = [[43 49 13  9 10]
     [12  1 21 -4 22]
     [-3 13  3 51  2]]
```
이런 연산을 하는 프로그램을 만들어라. 단, apply_along_axis() 함수를 이용하라.

In [ ]:
import numpy as np

def solve(row):
    max_val = row.max()
    min_val = row.min()
    row[row == max_val] += 5
    row[row == min_val] -= 5
    return row

a = np.array([[38, 44, 13, 9, 10],
              [12, 6, 16, 1, 17],
              [2, 13, 8, 46, 7]])
result = np.apply_along_axis(solve, axis=0, arr=a)
print(result)

In [ ]:
import numpy as np

def solve(row):
    max_idx = row.argmax()
    min_idx = row.argmin()
    row[max_idx] += 5
    row[min_idx] -= 5
    return row

a = np.array([[38, 44, 13, 9, 10],
              [12, 6, 16, 1, 17],
              [2, 13, 8, 46, 7]])
result = np.apply_along_axis(solve, axis=0, arr=a)
print(result)

### 문제 9.
예제 14에서 사용한 'fake_student_records.csv' 파일을 읽어서, 각 학생들의 8 번 과제 중에서 최저 점수를 제외한 7 번 시험의 평균을 구하여 소숫점 첫째 자리까지 콘솔에 출력하라. 정답은 다음과 같아야 한다.
```
[75.3 69.6 74.3 78.  77.4 80.1 76.6 91.1 77.6 72.3 82.7 82.  82.6 72.7
 78.7 86.3 81.  81.7 82.9 82.7 79.1 83.1 78.3 70.4 72.3 76.6 80.6 74.6
 81.9 75.6 80.7 71.1 77.6 77.7 71.3 74.9 77.3 76.4 80.  82.1 72.  72.7
 76.4 76.9 75.3 76.7 86.7 79.1 74.3 72.1 86.9 67.7 78.1 81.9 76.9 82.3
 73.1 84.6 73.4 81.1 80.6 81.3 70.1 75.  84.9 79.4 79.4 71.1 74.1 87.
 79.3 72.  80.6 79.4 72.7 84.6]
```

In [ ]:
import csv
import numpy as np

score = []

with open('fake_student_records.csv', mode='r', encoding='utf-8') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
        scores = [int(row[f'과제{i}']) for i in range(1, 9)]
        scores.sort()
        scores.pop(0)
        score.append(sum(scores)/7)

result = np.round(score, 1)
print(result, end="")

'



'

In [ ]:
import numpy as np

print("### array_x(8 bit int) ###", end="\n")
array_x = np.arange(8, dtype=np.int8) # 8비트 -128 ~ 127
print(array_x, end="\n")
array_x = array_x + 123 # 브로드 케스팅
print(array_x, end="\n")

print("### array_y(16 bit int) ###", end="\n")
array_y = np.arange(8, dtype=np.int16) # 16비트 -32758 ~ 32767
print(array_y, end="\n")
array_y = array_y + 516 # 브로드 케스팅
print(array_y, end="\n")

In [ ]:
import numpy as np

print("### array_x(linspace) ###", end="\n")
array_x = np.linspace(0, 2, 3)
print(array_x, end="\n")

print("### array_y(logspace) ###", end="\n")
array_y = np.logspace(0, 2, 3)
print(array_y, end="\n")

In [ ]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)
array_x = np.logspace(0, 100, 3)
print(array_x, end="")

In [ ]:
import numpy as np

test_array = np.arange(2, 25, 2, dtype=np.int16)

print(test_array, end="\n")
print(test_array.reshape(3,4), end="\n")
print(test_array.reshape(3,-1), end="\n")
print(test_array.reshape(-1,4), end="\n")